M48
; DRILL file {KiCad (6.0.7)} date Tue Aug 16 13:58:07 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-16T13:58:07+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0335
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X5.25Y-2.6
X5.25Y-3.1
X5.25Y-3.6
X5.55Y-2.6
X5.55Y-3.1
X5.55Y-3.6
T2
X4.4Y-3.1016
X4.4Y-3.2
T3
X6.0Y-2.6
X6.0Y-3.1
X6.0Y-3.6
X6.1Y-2.6
X6.1Y-3.1
X6.1Y-3.6
T0
M30
